services:
  ebook-sender-bot:
    image: ghcr.io/monlor/ebook-sender-bot:latest
    container_name: ebook-sender-bot
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - APP_MODE=prod
      - MAX_SEND_LIMIT=10
      - FORMAT=epub
      - EMAIL_PROVIDER=config
      - DB=sqlite
      - DB_NAME=/app/storage/ebook-sender-bot.db
      - SMTP_HOST=smtp.fastmail.com
      - SMTP_PORT=465
      - SMTP_USERNAME=${FASTMAIL_USERNAME}
      - SMTP_PASSWORD=${FASTMAIL_PASSWORD}
      - BOT_TOKEN=${EBOOK_SENDER_BOT_TOKEN}
      - DEVELOPER_CHAT_ID=${EBOOK_SENDER_BOT_DEVELOPER_CHAT_ID}
    volumes:
      - ebook-sender-bot-storage:/app/storage
    labels:
      - com.centurylinklabs.watchtower.enable=false

volumes:
  ebook-sender-bot-storage:
